CREATE TABLE IF NOT EXISTS DEPARTMENT (
     EMPLOYEE_ID TEXT,
     NAME TEXT,
     DEPARTMENT_ID TEXT,
     SALARY REAL
);

INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, SALARY) VALUES
      ('100', 'STEVEN KING', '90',  24000),
      ('101', 'NEENA KOCHAR', '20',  17000),
      ('102', 'LEX DECHAAN', '80' , 9000),
      ('103', 'BRUCE LEE', '40', 4800),
      ('104', 'DIANA WILLS', '60',24000),
      ('105', 'VALLI PATOR', '50',  4200),
      ('1973', 'LUV HAMI', '10',  5000),
      ('106', 'DAVID AUSTIN', '70', 6000);

SELECT COUNT(DEPARTMENT_ID) AS Departments
FROM DEPARTMENT;

SELECT SUM(SALARY) AS Total_salary
FROM DEPARTMENT;

SELECT AVG(SALARY) AS Average_salary
FROM DEPARTMENT;

SELECT MIN(SALARY) AS Minimum_salary
FROM DEPARTMENT;

SELECT MAX(SALARY) AS Maximum_salary
FROM DEPARTMENT;